name: artifact-hash

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "发版 版本号 tag"
        default: 'v1.9.1'
        type: string
      php-version:
        required: true
        description: "PHP 版本号 "
        default: 'v8.1.32,v8.2.28,v8.3.19,v8.4.5'
        type: string
      enable_upload_cloud_object_storage:
        required: false
        type: boolean
        description: "上传到云对象存储 (默认不需要上传）"

jobs:
  generate-artifact-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show Release File Hash
        run: |
          bash sapi/scripts/generate-artifact-hash.sh --version ${{ inputs.version }} --php-version ${{ inputs.php-version }}

      - name: production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.version }}-sha256sum
          retention-days: 90
          path: |
            ${{ inputs.version }}-sha256sum

      - name: upload artifacts to cloud object storage
        if: ${{ 0 && (github.repository == 'swoole/swoole-cli') && (inputs.enable_upload_cloud_object_storage == true) }}
        env:
          OSS_SECRET_ID: ${{ secrets.QCLOUD_OSS_SECRET_ID }}
          OSS_SECRET_KEY: ${{ secrets.QCLOUD_OSS_SECRET_KEY }}
          OSS_BUCKET: ${{ vars.QCLOUD_OSS_BUCKET }}
          OSS_REGION: ${{ vars.QCLOUD_OSS_REGION }}
        run: |
          bash sapi/scripts/tencent-cloud-object-storage.sh --upload-all --swoole-cli-version  ${{ inputs.version }}

