name: artifact-hash

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "发版 版本号 tag"
        default: 'v5.1.6.0'
        type: string

jobs:
  generate-artifact-hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show Release File Hash
        run: ｜
          bash sapi/scripts/generate-artifact-hash.sh --version ${{ inputs.version }}

      - name: production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.version }}-sha256sum
          retention-days: 90
          path: |
            ${{ inputs.version }}-sha256sum
