name: build-php-cli-linux-aarch64

on: [ push, pull_request ]

env:
  BUILD_PHP_VERSION: 8.2.11

jobs:
  linux-aarch64:
    if: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Source Code
        run: |
          echo $PATH
          env
          docker info
          id -u
          id -g
          who
          cat /etc/os-release
          hostnamectl
          uname -s
          uname -m
          uname -r
          export IPV6=$(ip -6 address show  | grep inet6 | awk '{print $2}' | cut -d'/' -f1 | sed -n '2p')
          export IPV4=$(ip -4 address show  | grep inet | grep -v 127.0.0 | awk '{print $2}' | cut -d'/' -f1 | sed -n '1p')
          echo $IPV4
          echo $IPV6
          echo "X_IPV6=${IPV6}" >> $GITHUB_ENV
          echo "X_IPV4=${IPV4}" >> $GITHUB_ENV

          # git submodule update --init

          sudo mkdir -p /usr/local/swoole-cli
          uid=$(id -u) && gid=$(id -g) && sudo chown -R ${uid}:${gid} /usr/local/swoole-cli

          mkdir -p ${{ github.workspace }}/var/build-github-action-container/

      - name: Cache PHP Runtime
        uses: actions/cache@v3
        id: php-runtime-cache
        with:
          path: ${{ github.workspace }}/bin/runtime
          key: ${{ runner.os }}-aarch64-php-runtime

      - name: Cache PHP Vendor
        uses: actions/cache@v3
        id: php-vendor-cache
        with:
          path: ${{ github.workspace }}/vendor
          key: ${{ runner.os }}-aarch64-php-vendor

      - name: Cache Dependency Source Code Tarball
        uses: actions/cache@v3
        id: dependency-cache
        with:
          path: ${{ github.workspace }}/pool/
          key: ${{ runner.os }}-aarch64-pool

      - name: Cache all-library
        uses: actions/cache@v3
        id: all-library-cache
        with:
          path: /usr/local/swoole-cli
          key: ${{ runner.os }}-aarch64-all-library

      - name: Cache swoole-cli-builder-image
        uses: actions/cache@v3
        id: swoole-cli-builder-image-aarch64-cache
        with:
          path: ${{ github.workspace }}/var/build-github-action-container/swoole-cli-builder-image.tar
          key: ${{ runner.os }}-aarch64-swoole-cli-builder-image

      - name: Prepare Libraries and Extensions
        run: |
          set -x
          bash sapi/download-box/download-box-get-archive-from-container.sh

      - name: Prepare QEMU
        run: |
          set -x
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Prepare swoole-cli-builder-image
        run: |
          if [ -f ${{ github.workspace }}/var/build-github-action-container/swoole-cli-builder-image.tar ] ; then
              docker load -i  ${{ github.workspace }}/var/build-github-action-container/swoole-cli-builder-image.tar
          else
              sh .github/workflows/build-alpine-builder-container.sh --platform "linux/arm64"
          fi

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
          # image: docker.io/jingjingxyk/build-swoole-cli:all-dependencies-alpine-3.17-php8-v1.0.0-aarch64-20230917T124401Z
          image: swoole-cli-builder:latest
          options: -v ${{ github.workspace }}:/work -w /work -e BUILD_PHP_VERSION=${{ env.BUILD_PHP_VERSION }} -v /usr/local/swoole-cli:/usr/local/swoole-cli
          run: |
            set -eux
            uname -m
            bash  setup-php-runtime.sh
            export PATH=/work/bin/runtime:$PATH  # 容器已经内置 php 和 composer
            alias php="php -d curl.cainfo=/work/bin/runtime/cacert.pem -d openssl.cafile=/work/bin/runtime/cacert.pem"

            # sed -i 's/mirrors.tuna.tsinghua.edu.cn/dl-cdn.alpinelinux.org/g' /etc/apk/repositories
            # sed -i 's/mirrors.ustc.edu.cn/dl-cdn.alpinelinux.org/g' /etc/apk/repositories

            sh  sapi/quickstart/linux/alpine-init.sh --mirror ""
            composer update --no-dev  --optimize-autoloader

            php prepare.php +inotify +apcu +ds +xlswriter +ssh2 +pgsql -mongodb --with-swoole-pgsql=1

            bash make-install-deps.sh

            # bash sapi/quickstart/mark-install-library-cached.sh

            bash make.sh all-library
            bash make.sh config
            bash make.sh build
            bash make.sh archive

      - name: Show Build Result
        uses: addnab/docker-run-action@v3
        with:
          # image: docker.io/jingjingxyk/build-swoole-cli:all-dependencies-alpine-3.17-php8-v1.0.0-aarch64-20230917T124401Z
          image: swoole-cli-builder:latest
          options: -v ${{ github.workspace }}:/work -w /work
          run: |
            ./thirdparty/php-src/sapi/cli/php -v
            ./thirdparty/php-src/sapi/cli/php -m
            ./thirdparty/php-src/sapi/cli/php --ri gd
            ./thirdparty/php-src/sapi/cli/php --ri swoole
            ./thirdparty/php-src/sapi/cli/php --ri pgsql
            file ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php
            readelf -h ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php
            ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php -r "echo PHP_VERSION;"
            ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php ./vendor/bin/phpunit ./sapi/src/UnitTest/MainTest.php  --list-tests
            ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php ./vendor/bin/phpunit ./sapi/src/UnitTest/MainTest.php

      - name: production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: php-cli-linux-aarch64-${{ env.BUILD_PHP_VERSION }}
          retention-days: 7
          path: ./bin/php-${{ env.BUILD_PHP_VERSION }}/bin/php
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: swoole-cli-*-linux-arm64.tar.xz
