name: build-swoole-cli-macos-x86_64

on: [ push, pull_request ]

jobs:
  macos-x86_64:
    if: 1
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare build environment
        run: |
          env
          echo $HOME
          brew install  wget curl  libtool automake gettext coreutils re2c binutils llvm
          brew uninstall --ignore-dependencies oniguruma
          brew uninstall --ignore-dependencies brotli
          brew uninstall --ignore-dependencies freetype
          brew uninstall --ignore-dependencies zstd
          brew uninstall --ignore-dependencies capstone
          which glibtool
          ln -sf /usr/local/bin/glibtool /usr/local/bin/libtool
          ln -sf /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
          sudo  xcode-select --switch /Applications/Xcode.app
          # export MACOSX_DEPLOYMENT_TARGET=12.6
          git submodule update --init

      - name: Prepare runtime
        run: |
          sudo mkdir -p pool/lib
          sudo mkdir -p pool/ext
          sudo mkdir -p bin/runtime
          sudo bash  sapi/quickstart/setup-php-runtime.sh
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH
          sudo bash sapi/download-box/download-box-get-archive-from-server.sh
      - name: prepare
        run: |
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH
          sudo composer update --no-dev  --optimize-autoloader
          sudo php prepare.php --without-docker=1  --with-build-type=release  +ds +apcu --with-global-prefix=${HOME}/.swoole-cli
          # sudo php prepare.php --without-docker=1  --with-build-type=release  +ds +apcu
      - name: Cache all-library
        uses: actions/cache@v3
        id: all-library-cache
        with:
          path: ~/.swoole-cli
          # path: /usr/local/swoole-cli
          key: ${{ runner.os }}-build-all-library
      - name: Build all-library
        if: ${{ steps.all-library-cache.outputs.cache-hit != 'true' }}
        run: |
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH
          sudo chmod a+x ./make.sh
          sudo ./make.sh all-library

      - name: Build
        run: |
          export MACOSX_DEPLOYMENT_TARGET=12.6
          export PATH=${GITHUB_WORKSPACE}/bin/runtime:$PATH
          sudo chmod a+x ./make.sh
          sudo ./make.sh config
          sudo ./make.sh build
          sudo ./make.sh archive

      - name: Show Build Result
        run: |
          file ./bin/swoole-cli
          otool -L ./bin/swoole-cli
          ./bin/swoole-cli -r "echo PHP_VERSION;"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: swoole-cli-macos-x64
          retention-days: 7
          path: ./bin/swoole-cli
      - name: gh release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: swoole-cli-*-x64.tar.xz
          draft: true
          prerelease: true
